spring:
  application:
    name: starter-api
  profiles:
    default: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  info:
    build:
      enabled: true
    git:
      mode: full
    env:
      enabled: true

logging:
  register-shutdown-hook: true

starter:
  cors:
    allowed-origins: ${STARTER_CORS_ALLOWED_ORIGINS:http://localhost:8081}
